spring:
  cache:
    type: redis
  redis:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 3000
        min-idle: 0
        max-total: 300
    database: 0
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 60

